/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package automatedtimetableschedular;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdAddNewCourse = new javax.swing.JButton();
        cmdAddNewLecturer = new javax.swing.JButton();
        cmdAddNewClassroom = new javax.swing.JButton();
        cmdSetStudents = new javax.swing.JButton();
        cmdSetGroupClass = new javax.swing.JButton();
        cmdSetLecturerCourse = new javax.swing.JButton();
        cmdSetLecturerAvailability = new javax.swing.JButton();
        cmdCreateTimetable = new javax.swing.JButton();
        cmdExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Form");
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 126, 123));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("University Of Ilorin");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CIS Timetable");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatedtimetableschedular/unilorin-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));

        cmdAddNewCourse.setBackground(new java.awt.Color(255, 153, 0));
        cmdAddNewCourse.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdAddNewCourse.setForeground(new java.awt.Color(255, 255, 255));
        cmdAddNewCourse.setText("Add New Course");
        cmdAddNewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddNewCourseActionPerformed(evt);
            }
        });

        cmdAddNewLecturer.setBackground(new java.awt.Color(255, 153, 0));
        cmdAddNewLecturer.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdAddNewLecturer.setForeground(new java.awt.Color(255, 255, 255));
        cmdAddNewLecturer.setText("Add New Lecturer");
        cmdAddNewLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddNewLecturerActionPerformed(evt);
            }
        });

        cmdAddNewClassroom.setBackground(new java.awt.Color(255, 153, 0));
        cmdAddNewClassroom.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdAddNewClassroom.setForeground(new java.awt.Color(255, 255, 255));
        cmdAddNewClassroom.setText("Add New Classroom");
        cmdAddNewClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddNewClassroomActionPerformed(evt);
            }
        });

        cmdSetStudents.setBackground(new java.awt.Color(255, 153, 0));
        cmdSetStudents.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdSetStudents.setForeground(new java.awt.Color(255, 255, 255));
        cmdSetStudents.setText("Set Students In Class");
        cmdSetStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetStudentsActionPerformed(evt);
            }
        });

        cmdSetGroupClass.setBackground(new java.awt.Color(255, 153, 0));
        cmdSetGroupClass.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdSetGroupClass.setForeground(new java.awt.Color(255, 255, 255));
        cmdSetGroupClass.setText("Set Group Class");
        cmdSetGroupClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetGroupClassActionPerformed(evt);
            }
        });

        cmdSetLecturerCourse.setBackground(new java.awt.Color(255, 153, 0));
        cmdSetLecturerCourse.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdSetLecturerCourse.setForeground(new java.awt.Color(255, 255, 255));
        cmdSetLecturerCourse.setText("Set Course Lecturer");
        cmdSetLecturerCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetLecturerCourseActionPerformed(evt);
            }
        });

        cmdSetLecturerAvailability.setBackground(new java.awt.Color(255, 153, 0));
        cmdSetLecturerAvailability.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdSetLecturerAvailability.setForeground(new java.awt.Color(255, 255, 255));
        cmdSetLecturerAvailability.setText("Set Lecturer Availability");
        cmdSetLecturerAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSetLecturerAvailabilityActionPerformed(evt);
            }
        });

        cmdCreateTimetable.setBackground(new java.awt.Color(255, 153, 0));
        cmdCreateTimetable.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdCreateTimetable.setForeground(new java.awt.Color(255, 255, 255));
        cmdCreateTimetable.setText("Create Lecture Timetable");
        cmdCreateTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateTimetableActionPerformed(evt);
            }
        });

        cmdExit.setBackground(new java.awt.Color(255, 153, 0));
        cmdExit.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        cmdExit.setForeground(new java.awt.Color(255, 255, 255));
        cmdExit.setText("Exit");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmdExit, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cmdAddNewCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdAddNewLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdAddNewClassroom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdSetStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdSetGroupClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdSetLecturerCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdSetLecturerAvailability, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCreateTimetable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdAddNewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAddNewLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAddNewClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSetStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSetGroupClass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSetLecturerCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdSetLecturerAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdCreateTimetable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAddNewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddNewCourseActionPerformed
        // TO add new Course into the Db
        CourseRegistrationForm courseForm = new CourseRegistrationForm();
        courseForm.setVisible(true);
        
    }//GEN-LAST:event_cmdAddNewCourseActionPerformed

    private void cmdAddNewLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddNewLecturerActionPerformed
        // TO add new Lecturer into the Db
        LecturerFom lecturerForm = new LecturerFom();
        lecturerForm.setVisible(true);
    }//GEN-LAST:event_cmdAddNewLecturerActionPerformed

    private void cmdAddNewClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddNewClassroomActionPerformed
        // TO add new Classroom into the Db
        ClassroomForm classroomForm = new ClassroomForm();
        classroomForm.setVisible(true);
    }//GEN-LAST:event_cmdAddNewClassroomActionPerformed

    private void cmdSetStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetStudentsActionPerformed
        // TO Set student in class into the Db
        StudentClassForm studentClassForm = new StudentClassForm();
        studentClassForm.setVisible(true);
    }//GEN-LAST:event_cmdSetStudentsActionPerformed

    private void cmdSetGroupClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetGroupClassActionPerformed
        // TO Set student in Group class into the Db
        StudentGroupClassForm studentGroupClassForm = new StudentGroupClassForm();
        studentGroupClassForm.setVisible(true);
    }//GEN-LAST:event_cmdSetGroupClassActionPerformed

    private void cmdSetLecturerCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetLecturerCourseActionPerformed
        // TO Set Lecturer Course Assignment into the Db
        LecturerCourseAssignmentForm lecturerCourseAssignmentForm = new LecturerCourseAssignmentForm();
        lecturerCourseAssignmentForm.setVisible(true);
    }//GEN-LAST:event_cmdSetLecturerCourseActionPerformed

    private void cmdSetLecturerAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSetLecturerAvailabilityActionPerformed
        // TO Set Lecturer Availabiility into the Db
        LecturerAvailableForm lecturerAvailableForm = new LecturerAvailableForm();
        lecturerAvailableForm.setVisible(true);
    }//GEN-LAST:event_cmdSetLecturerAvailabilityActionPerformed

    private void cmdCreateTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateTimetableActionPerformed
        // TO create a new lecture Timetable
        int sem = 0;
        JOptionPane.showMessageDialog(MainForm.this, "Welcome to an Automated Timetable Schedular");
        do
        { 
          sem = Integer.parseInt(JOptionPane.showInputDialog(MainForm.this, "Enter the semester: 1 - Harmattan, 2 - Rain"));
        }while((sem < 1) || (sem > 2));
        System.out.println("********* Welcome to Automated TimeTable Application  ***********");
        System.out.println("\n** This application is developed based on Constraint Programming and Genetic Algorithm  **");
        System.out.println("\n***** Population Size = 3:  *****");
        //create Timetable 1
        System.out.println("\n***** Timetable 1 Generation *****");
        CreateTimeTable createTimeTable1 = new CreateTimeTable(sem);
        createTimeTable1.generateInitialPopulation();
        //create Timetable 2
        CreateTimeTable createTimeTable2 = new CreateTimeTable(sem);
        createTimeTable2.allocateClassMeetings();
        //create Timetable 2
        CreateTimeTable createTimeTable3 = new CreateTimeTable(sem);
        createTimeTable3.allocateClassMeetings();
        int i = 0;
        while(i < 5){
        //repair Timetable 1    
        createTimeTable1.initializeCounters();
        createTimeTable1.repairClassMeetings();
        createTimeTable1.repairLecturer();
        //repair Timetable 2
        createTimeTable2.initializeCounters();
        createTimeTable2.repairClassMeetings();
        createTimeTable2.repairLecturer();        
        //repair Timetable 3
        createTimeTable3.initializeCounters();
        createTimeTable3.repairClassMeetings();
        createTimeTable3.repairLecturer();
        ++i;
        }

        createTimeTable1.assignClassrroms();
        createTimeTable1.displayResult();
        System.out.println("\n***** The cost for Timetable 1: " + createTimeTable1.getCost());
               
        //generate Timetable 2
        System.out.println("\n\n***** Timetable 2 Generation *****");
        createTimeTable2.assignClassrroms();
        createTimeTable2.displayResult();
        System.out.println("\n***** The cost for Timetable 2: " + createTimeTable2.getCost());
        
        //generate Timetable 3
        System.out.println("\n\n***** Timetable 3 Generation *****");
        createTimeTable3.assignClassrroms();
        createTimeTable3.displayResult();
        System.out.println("\n***** The cost for Timetable 3: " + createTimeTable3.getCost()) ;
        
        //Getting the  best timatable out of the population of three timetable using the minimum cost
        int best = createTimeTable1.getCost();
        if(best < createTimeTable2.getCost() && best < createTimeTable3.getCost()) 
         { //display the best resulting timetable 
            System.out.printf("\n\n******* The best Timetable is Timetable 1 for %s semester: **********", createTimeTable1.semester); 
            createTimeTable1.displayResult(); 
            System.out.println("\n***** The cost for the best Timetable is: " + createTimeTable1.getCost());
         }
        else if(best > createTimeTable2.getCost() && createTimeTable2.getCost() < createTimeTable3.getCost()) 
         { //display the best resulting timetable 
            System.out.printf("\n\n******* The best Timetable is Timetable 2 for %s semester: **********", createTimeTable2.semester); 
            createTimeTable2.displayResult(); 
            System.out.println("\n***** The cost for the best Timetable is: " + createTimeTable2.getCost());
         }
        else if(best > createTimeTable3.getCost() && createTimeTable2.getCost() > createTimeTable3.getCost()) 
         { //display the best resulting timetable
            System.out.printf("\n\n******* The best Timetable is Timetable 3 for %s semester: **********", createTimeTable3.semester); 
            createTimeTable3.displayResult(); 
            System.out.println("\n***** The cost for the best Timetable is: " + createTimeTable3.getCost());
         }        
    }//GEN-LAST:event_cmdCreateTimetableActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        // TO perform exit operation
        this.setVisible(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cmdExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAddNewClassroom;
    private javax.swing.JButton cmdAddNewCourse;
    private javax.swing.JButton cmdAddNewLecturer;
    private javax.swing.JButton cmdCreateTimetable;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdSetGroupClass;
    private javax.swing.JButton cmdSetLecturerAvailability;
    private javax.swing.JButton cmdSetLecturerCourse;
    private javax.swing.JButton cmdSetStudents;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
