/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package automatedtimetableschedular;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class StudentGroupClassForm extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    ResultSet rs;
    int CSC, MAC, LIS, ICS, TCS;
    /**
     * Creates new form StudentGroupClassForm
     */
    public StudentGroupClassForm() {
        initComponents();
        DoConnect();        
    }
    
    public void DoConnect(){
        try {  
        String host = "jdbc:derby://localhost:1527/DbTimetable";
        String uName = "bprogrammer";
        String uPass = "password";
        //String uName = "BProgrammer";
        //String uPass = "bprogrammer";
        con = DriverManager.getConnection(host, uName, uPass);
        
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql = "SELECT * FROM TblStudentsGroup";
        rs = stmt.executeQuery(sql);
        
            cmdAddNew.setEnabled(false); 
            cmdSaveNew.setEnabled(true);
         //JOptionPane.showMessageDialog(Workers.this,"first name" + first_name);
            
        
      }
      catch (SQLException err) {
          JOptionPane.showMessageDialog(StudentGroupClassForm.this, err.getMessage());
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGroupId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chkCSC = new javax.swing.JCheckBox();
        chkMAC = new javax.swing.JCheckBox();
        chkLIS = new javax.swing.JCheckBox();
        chkICS = new javax.swing.JCheckBox();
        chkTCS = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cboLevelCSC = new javax.swing.JComboBox();
        cboLevelMAC = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboLevelLIS = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cboLevelICS = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cboLevelTCS = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboSemester = new javax.swing.JComboBox();
        txtCourseCode = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdAddNew = new javax.swing.JButton();
        cmdSaveNew = new javax.swing.JButton();
        cmdCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Students Group Class Form");
        setName("studentGroupClassForm"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Group Id:");

        txtGroupId.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        chkCSC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkCSC.setText("CSC");
        chkCSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCSCActionPerformed(evt);
            }
        });

        chkMAC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkMAC.setText("MAC");
        chkMAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMACActionPerformed(evt);
            }
        });

        chkLIS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkLIS.setText("LIS");
        chkLIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLISActionPerformed(evt);
            }
        });

        chkICS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkICS.setText("ICS");
        chkICS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkICSActionPerformed(evt);
            }
        });

        chkTCS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkTCS.setText("TCS");
        chkTCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTCSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Level:");

        cboLevelCSC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboLevelCSC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Level", "200 Level", "300 Level", "400 Level" }));

        cboLevelMAC.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboLevelMAC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Level", "200 Level", "300 Level", "400 Level" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Level:");

        cboLevelLIS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboLevelLIS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Level", "200 Level", "300 Level", "400 Level" }));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Level:");

        cboLevelICS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboLevelICS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Level", "200 Level", "300 Level", "400 Level" }));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Level:");

        cboLevelTCS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboLevelTCS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100 Level", "200 Level", "300 Level", "400 Level" }));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Level:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chkTCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkICS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkLIS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkMAC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(chkCSC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboLevelCSC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(cboLevelICS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboLevelLIS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboLevelMAC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboLevelTCS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkCSC)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboLevelCSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboLevelMAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkMAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLevelLIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkLIS))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboLevelICS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkICS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboLevelTCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkTCS))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Course Code:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Semester:");

        cboSemester.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rain", "Harmattan" }));

        txtCourseCode.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        cmdAddNew.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        cmdAddNew.setText("Add New");
        cmdAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddNewActionPerformed(evt);
            }
        });

        cmdSaveNew.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        cmdSaveNew.setText("Save New");
        cmdSaveNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaveNewActionPerformed(evt);
            }
        });

        cmdCancel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        cmdCancel.setText("Cancel");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cmdSaveNew, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdSaveNew)
                    .addComponent(cmdCancel))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 27)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 126, 123));
        jLabel9.setText("University Of Ilorin");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CIS Timetable");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automatedtimetableschedular/unilorin-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMACActionPerformed
        // TO set pointer when selected to ONE otherwise ZERO
        if(chkMAC.isSelected()){
            MAC = 1;    
        }
        else {
            MAC = 0;
        }
    }//GEN-LAST:event_chkMACActionPerformed

    private void chkLISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLISActionPerformed
       // TO set pointer when selected to ONE otherwise ZERO
        if(chkLIS.isSelected()){
            LIS = 1;    
        }
        else {
            LIS = 0;
        }
    }//GEN-LAST:event_chkLISActionPerformed

    private void chkICSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkICSActionPerformed
        // TO set pointer when selected to ONE otherwise ZERO
        if(chkICS.isSelected()){
            ICS = 1;    
        }
        else {
            ICS = 0;
        }
    }//GEN-LAST:event_chkICSActionPerformed

    private void chkTCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTCSActionPerformed
        // TO set pointer when selected to ONE otherwise ZERO
        if(chkTCS.isSelected()){
            TCS = 1;    
        }
        else {
            TCS = 0;
        }
    }//GEN-LAST:event_chkTCSActionPerformed

    private void cmdSaveNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaveNewActionPerformed
        // The code to Save the current record in the database table
            String sql;
            String Course_Code = txtCourseCode.getText();
            String Group_Id = txtGroupId.getText();
            String CSC_Level = cboLevelCSC.getSelectedItem().toString();
            String MAC_Level = cboLevelMAC.getSelectedItem().toString();
            String ICS_Level = cboLevelICS.getSelectedItem().toString();
            String TCS_Level = cboLevelTCS.getSelectedItem().toString();
            String LIS_Level = cboLevelLIS.getSelectedItem().toString();
            String Semester = cboSemester.getSelectedItem().toString();
            
            
     try {                 
           if((Course_Code.isEmpty()) || (Group_Id.isEmpty())){
               JOptionPane.showMessageDialog(StudentGroupClassForm.this, "Data not Saved!! Please ensure that all textboxes are filled");
           }
           else if((CSC == 0) &&(MAC == 0) && (ICS == 0) && (LIS == 0) && (TCS == 0)){
               JOptionPane.showMessageDialog(StudentGroupClassForm.this, "Data not Saved!! Please ensure you marked at least two courses' checkboxes");
           }
           else {
                stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                sql = "SELECT * FROM TblStudentsGroup where Group_Id = '" + Group_Id + "' AND Course_Code = '" + Course_Code + "'";
                rs = stmt.executeQuery(sql);
                if(rs.next()){
                   //check if the course has already been registered in the db
                    rs.updateString("Group_Id", Group_Id);
                    rs.updateString("Course_Code",  Course_Code); 
                    rs.updateString("Semester", Semester);
                    rs.updateInt("CSC", CSC);
                    rs.updateString("CSC_Level", CSC_Level);
                    rs.updateInt("MAC", MAC);
                    rs.updateString("MAC_Level", MAC_Level);
                    rs.updateInt("LIS", LIS);
                    rs.updateString("LIS_Level", LIS_Level);
                    rs.updateInt("ICS", ICS);
                    rs.updateString("ICS_Level", ICS_Level);
                    rs.updateInt("TCS", TCS);
                    rs.updateString("TCS_Level", TCS_Level);
                    rs.updateRow();
                    rs.close();
                    stmt.close();
                    cmdAddNew.setEnabled(true); 
                    cmdSaveNew.setEnabled(false);
                    JOptionPane.showMessageDialog(StudentGroupClassForm.this,"Data updated successfully!!!");
                }
                else {
                       //Save as new course
                    rs.close();
                    stmt.close();
                    stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    sql = "SELECT * FROM TblStudentsGroup";
                    rs = stmt.executeQuery(sql);
                    rs.moveToInsertRow();
                    rs.updateString("Group_Id", Group_Id);
                    rs.updateString("Course_Code",  Course_Code); 
                    rs.updateString("Semester", Semester);
                    rs.updateInt("CSC", CSC);
                    rs.updateString("CSC_Level", CSC_Level);
                    rs.updateInt("MAC", MAC);
                    rs.updateString("MAC_Level", MAC_Level);
                    rs.updateInt("LIS", LIS);
                    rs.updateString("LIS_Level", LIS_Level);
                    rs.updateInt("ICS", ICS);
                    rs.updateString("ICS_Level", ICS_Level);
                    rs.updateInt("TCS", TCS);
                    rs.updateString("TCS_Level", TCS_Level);
                    rs.insertRow();
                    rs.close();
                    stmt.close();
                    cmdAddNew.setEnabled(true); 
                    cmdSaveNew.setEnabled(false);
                    JOptionPane.showMessageDialog(StudentGroupClassForm.this,"New Record Saved Successfully");
                }
           }
        
      }
      catch (SQLException err) {
          JOptionPane.showMessageDialog(StudentGroupClassForm.this, err.getMessage());
      }
    }//GEN-LAST:event_cmdSaveNewActionPerformed

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        // TO cancel operation
        this.setVisible(false);
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void chkCSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCSCActionPerformed
        // TO set pointer when selected to ONE otherwise ZERO
        if(chkCSC.isSelected()){
            CSC = 1;    
        }
        else {
            CSC = 0;
        }
            
    }//GEN-LAST:event_chkCSCActionPerformed

    private void cmdAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddNewActionPerformed
        // TO add new record
        CSC = 0; MAC = 0; LIS = 0; ICS = 0;  TCS = 0;
        txtCourseCode.setText("");
        txtGroupId.setText("");
        cmdAddNew.setEnabled(false); 
        cmdSaveNew.setEnabled(true);
        chkCSC.setSelected(false);
        chkMAC.setSelected(false);
        chkLIS.setSelected(false);
        chkICS.setSelected(false);
        chkTCS.setSelected(false);
    }//GEN-LAST:event_cmdAddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGroupClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGroupClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGroupClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGroupClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGroupClassForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboLevelCSC;
    private javax.swing.JComboBox cboLevelICS;
    private javax.swing.JComboBox cboLevelLIS;
    private javax.swing.JComboBox cboLevelMAC;
    private javax.swing.JComboBox cboLevelTCS;
    private javax.swing.JComboBox cboSemester;
    private javax.swing.JCheckBox chkCSC;
    private javax.swing.JCheckBox chkICS;
    private javax.swing.JCheckBox chkLIS;
    private javax.swing.JCheckBox chkMAC;
    private javax.swing.JCheckBox chkTCS;
    private javax.swing.JButton cmdAddNew;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdSaveNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtGroupId;
    // End of variables declaration//GEN-END:variables
}
